### ISSUE TITLE
后台一直显示代理异常,一直在等待下载

### ISSUE THREAD

**Issue by gloomyzerg** [bowenpay/wechat-spider#17]
后台显示代理异常,是需要在哪里设置代理吗
不使用代理可以吗?

**Comment by yijingping** [comment]
@gloomyzerg 默认是不使用代理的，会显示代理异常，但不影响使用。 
可以发下 bin/downloader.py 打印出来的东西，看是否有报错？

**Comment by gloomyzerg** [comment]
wechatspider_downloader.stderr.log  日志内容

```
DEBUG 2016-11-03 10:53:53,492 __init__ 3896 139709332178752 version=0.2.3
DEBUG 2016-11-03 10:53:53,493 __init__ 3896 139709332178752 version=0.1.5
Traceback (most recent call last):
  File "/www/wechat-spider/bin/downloader.py", line 18, in <module>
    from wechat.downloaders import SeleniumDownloaderBackend
  File "/home/www/wechat-spider/wechat/downloaders.py", line 19, in <module>
    from .util import stringify_children
  File "/home/www/wechat-spider/wechat/util.py", line 24, in <module>
    real_pip = get_real_pip()
  File "/home/www/wechat-spider/wechat/util.py", line 18, in get_real_pip
    conn = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by yijingping** [comment]
`get_real_pip` 函数用来获取自己的公网ip，用来验证当前代理是否有效。它在程序初始化的时候会执行一次，去访问这个url `http://api.ipify.org`。
你的报错应该是访问超时了。
```
ip_check_url = 'http://api.ipify.org'
user_agent = 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0'
socket_timeout = 3

# Get real public IP address
def get_real_pip():
    req = urllib2.Request(ip_check_url)
    req.add_header('User-agent', user_agent)
    conn = urllib2.urlopen(req)
    page = conn.read()
    conn.close()
    return page
```

**Comment by gloomyzerg** [comment]
明白了 我这边访问不了 http://api.ipify.org  
我换个查询ip的地址试试 
非常感谢

**Comment by gloomyzerg** [comment]
@yijingping 我看到wechat/management  有获取代理IP 和检查代理IP的程序 
本身不是太懂python  我已经更换了获取代理IP的地址 我怎么去触发这个程序?

**Comment by yijingping** [comment]
你只要
1 启动代理检测脚本：`python manage.py checkproxies`
2 将新的代理加到数据库。downloader会自动使用检测成功的代理。
![image](https://cloud.githubusercontent.com/assets/2122123/19996214/fdaf999a-a298-11e6-8694-86c590581c9d.png)

**Comment by gloomyzerg** [comment]
谢谢 这个问题已经解决了 
昨天我也买了那个代理了  效果确实不好
代理慢的时候会挤压很多下载队列,成功的代理也少
