### ISSUE TITLE
Message: Can't load the profile.

### ISSUE THREAD

**Issue by gloomyzerg** [bowenpay/wechat-spider#21]
Message: Can't load the profile. Profile Dir: /tmp/tmpluVvmZ If you specified a log_file in the FirefoxBinary constructor, check it for details.

wechatspider_downloader.stderr.log 中提示此信息 现在无法下载
这个是什么问题呢?

**Comment by yijingping** [comment]
可以重新看下Readme，并发下你的系统环境信息，通常都是firefox版本或者系统环境问题

**Comment by gloomyzerg** [comment]
我是在树莓派上安装的
firefox版本  Mozilla Firefox 45.4.0 
之前在centos都可以正常运行

**Comment by zhangsir293** [comment]
我也遇到了同样的问题，系统是centos6.5 x64，firefox版本是60.2.1esr (64-bit)

**Comment by Rockyzsu** [comment]
DEBUG 2019-07-18 22:06:40,870 abstractdisplay 11035 140646748030784 DISPLAY=:1124
Message: Can't load the profile. Profile Dir: /tmp/tmpYDaRnd If you specified a log_file in the FirefoxBinary constructor, check it for details.

Traceback (most recent call last):
  File "bin/downloader.py", line 96, in <module>
    downloader.run()
  File "bin/downloader.py", line 77, in run
    with SeleniumDownloaderBackend(proxy=proxy) as browser:
  File "/home/cjw/workspace/wechat-spider/wechat/downloaders.py", line 42, in __enter__
    self.browser = self.get_browser(self.proxy)
  File "/home/cjw/workspace/wechat-spider/wechat/downloaders.py", line 90, in get_browser
    browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/home/cjw/anaconda3/envs/wx_spider/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 78, in __init__
    self.binary, timeout)
  File "/home/cjw/anaconda3/envs/wx_spider/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/cjw/anaconda3/envs/wx_spider/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/home/cjw/anaconda3/envs/wx_spider/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpYDaRnd If you specified a log_file in the FirefoxBinary constructor, check it for details.

(wx_spider) [cjw@localhost wechat-spider]$ selenium.common.exceptions.WebDriverException: Message: Can't load the profileCan't load the profile


OS：centos 6.5
3.10.0-862.11.6.el7.x86_64
