### ISSUE TITLE
提取时,发生错误  -------> extractor.py 

### ISSUE THREAD

**Issue by xiaocui-s** [bowenpay/wechat-spider#39]
帮忙看下这个错误吧!~
title
origin_title
source
content
words
abstract
avatar
Traceback (most recent call last):
  File "extractor.py", line 409, in <module>
    my_extractor.run()
  File "extractor.py", line 404, in run
    self.get_detail(body, data)
  File "extractor.py", line 381, in get_detail
    col_value = self.extract(content, col_rules, {'data': result})
  File "extractor.py", line 335, in extract
    extractor = XPathExtractor(res, rule["data"])
  File "/home/xiaocui/cui/xiaocui/wechat-spider/wechat/extractors.py", line 130, in __init__
    self.tree = etree.parse(StringIO(content), htmlparser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1828, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118072)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1729, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:116899)
  File "src/lxml/parser.pxi", line 1063, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:110886)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 646, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105963)
  File "<string>", line 0
lxml.etree.XMLSyntaxError

**Comment by xiaocui-s** [comment]
..

**Comment by yijingping** [comment]
提取avatar字段的时候发生错误， 可能这篇文章的头图有什么特殊之处。 

需要你把当前解析的文章的地址告诉我一下

**Comment by xiaocui-s** [comment]
http://mp.weixin.qq.com/s?src=3&timestamp=1484101718&ver=1&signature=*cRiWzNuPplir1U4zcNXPxdVxZ0isxTn9y*FvqZGAAmywY7BD-Ug2H8quZVVJOZrM0HOiRw7msXRBVg77J0*ESBgUynJV6H4xCIES1-ce6nsCqynm7wC48nAteCW89CpMPLfrz8ADvFdqQdZs8G5fd3a1AmesvZbJ6dgB4QJucg=

是单独添加的一个URL

**Comment by yijingping** [comment]
我添加上面的链接爬取的时候，没有出现问题，如下图：

![image](https://cloud.githubusercontent.com/assets/2122123/21877042/44b3a5c4-d8c3-11e6-9e2d-d54a54710d45.png)

你看下代码是否是最新的

**Comment by xiaocui-s** [comment]
难道是, 本地下载的lxml 包有问题吗

**Comment by xiaocui-s** [comment]
好的,我再调一下,  谢谢!
