### ISSUE TITLE
爬虫部署之后，过几天就不能爬取了，重启停了一天之后也不好使

### ISSUE THREAD

**Issue by banqinghong** [bowenpay/wechat-spider#42]
日志文件中：其他日志文件都是空的，Downloader报错如下：
DEBUG 2017-03-10 16:39:37,900 remote_connection 17038 140391779444544 Finished Request
ERROR 2017-03-10 16:39:37,901 downloaders 17038 140391779444544 Message: Unable to locate element: {"method":"xpath","selector":"//div[@class='txt-box']/p[@class='info']/label"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/driver-component.js:10723)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/driver-component.js:10732)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/command-processor.js:12614)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/command-processor.js:12619)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/command-processor.js:12561)
Traceback (most recent call last):
  File "/root/wechat-spider/wechat/downloaders.py", line 102, in download_wechat
    if self.visit_wechat_topic_list(wechatid):
  File "/root/wechat-spider/wechat/downloaders.py", line 188, in visit_wechat_topic_list
    element_wechat = browser.find_element_by_xpath("//div[@class='txt-box']/p[@class='info']/label")
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 258, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: {"method":"xpath","selector":"//div[@class='txt-box']/p[@class='info']/label"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/driver-component.js:10723)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/driver-component.js:10732)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/command-processor.js:12614)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/command-processor.js:12619)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmprZaDO2/extensions/fxdriver@googlecode.com/components/command-processor.js:12561)
DEBUG 2017-03-10 16:39:37,903 remote_connection 17038 140391779444544 DELETE http://127.0.0.1:46313/hub/session/30f3cc8c-1257-4f04-b4a3-8175dc26eb00/cookie {"sessionId": "30f3cc8c-1257-4f04-b4a3-8175dc26eb00"}

**Comment by yijingping** [comment]
问题出在搜索微信号的下一个页面，用于获取第一个被搜索到的微信号。
![wechatimg19](https://cloud.githubusercontent.com/assets/2122123/23908803/f55a0400-090f-11e7-80b0-7d7977feb557.jpeg)

我本地调试了一下，发现获取没有问题。你看一下是不是你的ip被封了

**Comment by banqinghong** [comment]
![Uploading 1489988474(1).png…]()

我自己找了几个服务器配置了代理之后，上周还能够正常爬取文章，不过IP过一段时间就出现什么需要验证码了，应该是被封了，然后停了2天之后，今天再次添加，代理那里显示正常，但是会出现等待下载的文章不断增加，但是文章都没有下载下来的情况。

**Comment by banqinghong** [comment]
![Uploading 1489988474(1).png…]()

**Comment by banqinghong** [comment]
Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


这是downloadout日志里面的一句话

**Comment by yijingping** [comment]
启动firefox失败了，可能Xvfb没安装，或者glib版本不对。 建议服务器使用centos 7.0

**Comment by banqinghong** [comment]
getNewIp.py里面的代码里面，爬虫部署的地方，我将域名更改为内网的IP地址（我是在内网访问的）http://192.168.1.18:8001/wechat/proxy/1/edit/，我这只是测试想看一下效果。结果会报404错误  错误如下：

####: localhost.localdomain
####: localhost4
####: localhost4.localdomain4
####: localhost.localdomain
####: localhost6
####: localhost6.localdomain6
####: 127.0.0.1
####: 127.0.0.1
new ip: 127.0.0.1

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /wechat/proxy/1/edit/</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>POST</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http://192.168.1.18:8001/wechat/proxy/1/edit/</td>
      </tr>
      
      <tr>
        <th>Raised by:</th>
        <td>wechat.views.proxy_edit</td>
      </tr>
      
    </table>
  </div>
  <div id="info">
    
      <p>No Proxy matches the given query.</p>
    
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>

sleep 1 second

**Comment by banqinghong** [comment]
我就是想试一下怎么把VPS上面的IP传到爬虫项目里面，求大神解答一下

**Comment by yijingping** [comment]
如果你的爬虫机器也有一个外网ip的话：

> 首先，你需要在vps上搭建一个代理，然后在vps上执行getNewIp.py，该脚本会获取本vps的外网ip，提交给爬虫所在的机器。
> 然后，爬虫会把这个ip存到数据库中，当downloader.py执行的时候，会使用该ip作为代理。

如果没有外网ip，你可能需要一台中介服务器，流程如下：

> vps--提交-->中介服务器<--获取--爬虫机器

**Comment by banqinghong** [comment]
我在vps上面部署getNewIp.py后，运行时会报出上面的404错误，爬虫项目里面也获取不到IP。是这个链接地址的问题吗？在vps上面通过外网地址是能够访问爬虫系统的

**Comment by yijingping** [comment]
getNewIp.py 你需要改一些提交url的地址，改成你自己的爬虫系统的。

![image](https://cloud.githubusercontent.com/assets/2122123/24550459/b50afafa-1650-11e7-8fdd-f271c9406658.png)

**Comment by banqinghong** [comment]
我这边URL地址是改过的，把前面的域名那一块改成了我爬虫项目的外网IP和端口（http://61.55.125.218:23333/wechat/proxy/1/edit/）。后面的路径没有改变。在VPS上面通过这个IP和端口是能够访问爬虫系统的，我也试过http://61.55.125.218:23333/admin/wechat/proxy/add这个是需要先登陆才能使用的，但是这个脚本里面没有登陆这个程序段。因为不是做开发的，所以对python不是很懂。这个URL路径应该是那一个啊。我使用你上面图中那个地址一直都是报的404

**Comment by banqinghong** [comment]
@yijingping  这个url地址是怎么确定的呢？我只是修改域名的话发现并不能够提交数据到爬虫系统上面，是不是后面的路径也需要修改
