### ISSUE TITLE
程序启动后 downloader.py 报错

### ISSUE THREAD

**Issue by guyfar** [bowenpay/wechat-spider#46]
程序启动后，downloader.py 报如下错误，实在找不到什么原因了，希望协助解答，谢谢。
说明：本机已安装 firfox36.0       本机系统为：macOS 10.12.3

提示报错信息如下：
# 未被限制,可以下载
[Errno 8] Exec format error
Traceback (most recent call last):
  File "bin/downloader.py", line 96, in <module>
    downloader.run()
  File "bin/downloader.py", line 77, in run
    with SeleniumDownloaderBackend(proxy=proxy) as browser:
  File "/Users/gaoxiaofei/pywww/wechat-spider/wechat/downloaders.py", line 42, in __enter__
    self.browser = self.get_browser(self.proxy)
  File "/Users/gaoxiaofei/pywww/wechat-spider/wechat/downloaders.py", line 90, in get_browser
    browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 145, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by guyfar** [comment]
已解决，是因为selenium版本太高，降低到2.52.0就好了
