### ISSUE TITLE
通过公众号添加后无法爬取啊

### ISSUE THREAD

**Issue by linuxclab** [bowenpay/wechat-spider#49]
同过公众号添加后看不到爬虫爬取啊，所有脚本程序启动都正常。

**Comment by northleafup** [comment]
@linuxclab  您好，您的问题是否解决了呢， 我运行了四个脚本也没报错，也没有输出，不知道啥原因
<img width="1245" alt="1" src="https://cloud.githubusercontent.com/assets/15024762/25792432/2be844e6-33f9-11e7-99f0-9903519ac9d0.png">

**Comment by yijingping** [comment]
你主要看这4个脚本是否运行正常，是否打印了什么异常日志：
```
$ python bin/scheduler.py
$ python bin/downloader.py
$ python bin/extractor.py
$ python bin/processor.py
```

**Comment by linuxclab** [comment]
全都正常啊，没有报错，而且可以进入后台，也能添加公众号列表。

**Comment by linuxclab** [comment]
E:\360Downloads\wechat-spider-master\bin>python downloader.py
DEBUG 2017-05-16 20:28:37,062 __init__ 820 5520 version=0.2.3
DEBUG 2017-05-16 20:28:37,131 __init__ 820 5520 version=0.2.1
DEBUG 2017-05-16 20:48:33,223 downloader 820 5520 {u'wechatid': u'sysulib', u'ki
nd': 0, u'wechat_id': 11}
# 鏈闄愬埗,鍙互涓嬭浇
DEBUG 2017-05-16 20:48:33,565 __init__ 820 5520 param: "['Xvfb', '-help']"
DEBUG 2017-05-16 20:48:33,568 __init__ 820 5520 command: ['Xvfb', '-help']
DEBUG 2017-05-16 20:48:33,569 __init__ 820 5520 joined command: Xvfb -help
DEBUG 2017-05-16 20:48:33,588 __init__ 820 5520 OSError exception: [Error 2]
cmd=['Xvfb', '-help']
OSError=[Error 2]
Program install error!
Traceback (most recent call last):
  File "downloader.py", line 96, in <module>
    downloader.run()
  File "downloader.py", line 77, in run
    with SeleniumDownloaderBackend(proxy=proxy) as browser:
  File "E:\wechat-spider-master\wechat\downloader
s.py", line 40, in __enter__
    self.display = self.get_display()
  File "E:\wechat-spider-master\wechat\downloader
s.py", line 64, in get_display
    display = Display(visible=0, size=(1024, 768))
  File "D:\Python27\lib\site-packages\pyvirtualdisplay\display.py", line 34, in
__init__
    self._obj = self.display_class(
  File "D:\Python27\lib\site-packages\pyvirtualdisplay\display.py", line 52, in
display_class
    cls.check_installed()
  File "D:\Python27\lib\site-packages\pyvirtualdisplay\xvfb.py", line 38, in che
ck_installed
    ubuntu_package=PACKAGE).check_installed()
  File "D:\Python27\lib\site-packages\easyprocess\__init__.py", line 180, in che
ck_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Error 2]
Program install error!
