### ISSUE TITLE
为何下载时会报以下的错误呢？

### ISSUE THREAD

**Issue by northleafup** [bowenpay/wechat-spider#51]
<img width="883" alt="2" src="https://cloud.githubusercontent.com/assets/15024762/25794447/82d496ec-3403-11e7-81e1-86f4ab5d607c.png">
我用的是firefox53 (官网上的36下载后报已损坏的错误）

**Comment by yijingping** [comment]
就是firefox版本不对的原因。 你从这里下会有问题吗？https://ftp.mozilla.org/pub/firefox/releases/36.0/mac/zh-CN/

**Comment by northleafup** [comment]
@yijingping 您好，我下载了36的版本，但是下载后firefox 总是自动升级到最新版本，我选择了不让它自动更新，但不起作用，请问这个问题您是如何处理的呢？

**Comment by northleafup** [comment]
@yijingping  您好，我刚刚试出来的一个方法，将/Users/<name>/Library/Caches/Mozilla//updates/Applications/Firefox/  路径下的文件改为root权限，同时将它们改为无权限(sudo chmod 000 *)，这样Firefox就不能再升级了，谢谢，我再试一下能不能下载公众号的文章。

**Comment by northleafup** [comment]
@yijingping  您好，为何右上角的代理状态为异常呢？需要设置哪呢，另外开始下载后，显示如下信息是何意思呢？（Finished Request ）
<img width="437" alt="1" src="https://cloud.githubusercontent.com/assets/15024762/25941353/b18ead6e-366b-11e7-9314-1e38187e9607.png">

**Comment by northleafup** [comment]
@yijingping 您好在执行process.py脚本的时候报以下的错误：
EERFFWq/hFgADUMN4RzT6/OAAAAAElFTkSuQmCC\"/> <p class=\"toast_content\">已留言</p> </div> </div> </div> </div><iframe src=\"http://mp.weixin.qq.com/mp/readtemplate?t=appmsg/cspsupport_test_tmpl&amp;level=1\" style=\"display: none;\"></iframe><iframe src=\"http://mp.weixin.qq.com/mp/readtemplate?t=appmsg/cspsupport_test_tmpl&amp;level=2\" style=\"display: none;\"></iframe></body></html>", "like_num": 0, "avatar": "http://mmbiz.qpic.cn/mmbiz_jpg/4huZu0wMGticNlDj6ibgMzPicwlEEyricULCiaeo36CQsMic57E1Gho1C0opdVNElHeQSDciadKAA6AU5y1ia7YderKqQw/0?wx_fmt=jpeg", "words": 3499, "wechat_id": 1, "read_num": 0}
Traceback (most recent call last):
  File "bin/processor.py", line 57, in <module>
    processor.run()
  File "bin/processor.py", line 52, in run
    self.process(data)
  File "bin/processor.py", line 37, in process
    backend.process(data)
  File "/Users/northleaf/git/bowenpay-weichat-spider/wechat/processors.py", line 48, in process
    C.objects.update_or_create(uniqueid=params['uniqueid'], defaults=params)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 422, in update_or_create
    obj, created = self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 971, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x92\\x97</...' for column 'content' at row 1")

这个错误是什么原因呢（我用的是Mysql）？
另外，如何显示留言呢？谢谢

**Comment by yijingping** [comment]
这说明文章已经爬取并解析好了，在存储的时候出错了。 有可能是你的数据库编码有问题。 你的mysql版本号是多少？ 编码设为utf8mb4了吗？

**Comment by yijingping** [comment]
现在没有解析留言功能，需要改下配置规则文件和数据库结构，才能存。

**Comment by northleafup** [comment]
@yijingping  您好，编码功能我已调好，请问如何修改规则文件与数据库结构才能存储留言功能呢，谢谢！

**Comment by yijingping** [comment]
在 `bin/extractor.py` 中，修改变量 `NORMAL_RULES` 和 `DETAIL_RULES`。 他们分别用于解析通过微信号爬取的文章 和 通过url爬取的文章。
![image](https://cloud.githubusercontent.com/assets/2122123/26025645/9c62cfb0-381e-11e7-85bd-66a76404d75f.png)

1）在数据库中新增messages字段
2）修改变量 `NORMAL_RULES` 和 `DETAIL_RULES`
在变量列表中，仿照 avatar 字段的值，新增一个messages字段。 然后使用 xpath、 python规则，将留言中的头像、昵称、内容 都提取出来，用json字符串的形式存储在

**Comment by northleafup** [comment]
@yijingping 谢谢，我按您说的试一下。
