### ISSUE TITLE
bin/downloader.py 运行失败

### ISSUE THREAD

**Issue by asseywang** [bowenpay/wechat-spider#67]
- Mac  osx系统
- python 2.7 
- 运行成功后下载关键词时报错

 `/wechat-spider/bin/downloader.py
DEBUG 2018-01-24 15:04:03,946 __init__ 37378 140736030864192 version=0.2.3
DEBUG 2018-01-24 15:04:03,949 __init__ 37378 140736030864192 version=0.1.5
DEBUG 2018-01-24 15:06:53,452 downloader 37378 140736030864192 {u'kind': 3, u'word': u'\u4ea4\u4e92\u8bbe\u8ba1'}
# 未被限制,可以下载
Message: Can't load the profile. Profile Dir: /var/folders/8f/5nvdky5x44gcd_cpwdjzz4s40000gn/T/tmpGCTwmP If you specified a log_file in the FirefoxBinary constructor, check it for details.
Traceback (most recent call last):

  File "bin/downloader.py", line 96, in <module>
    downloader.run()
  File "wechat-spider/bin/downloader.py", line 77, in run
    with SeleniumDownloaderBackend(proxy=proxy) as browser:
  File "wechat-spider/wechat/downloaders.py", line 42, in __enter__
    self.browser = self.get_browser(self.proxy)
  File "wechat-spider/wechat/downloaders.py", line 90, in get_browser
    browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 78, in __init__
    self.binary, timeout)
  File "lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/8f/5nvdky5x44gcd_cpwdjzz4s40000gn/T/tmpGCTwmP If you specified a log_file in the FirefoxBinary constructor, check it for details.
`

**Comment by asseywang** [comment]
不知道为啥，我把程序切换到pycharm中执行就好了。
