### ISSUE TITLE
bin/downloader.py 自动打开 firefox 报错

### ISSUE THREAD

**Issue by onestarshang** [bowenpay/wechat-spider#7]
```
# 未被限制,可以下载
DEBUG 2016-09-29 23:23:39,015 remote_connection 85800 140735118328576 POST http://127.0.0.1:60960/hub/session {"requiredCapabilities": {}, "desiredCapabilities": {"binary": "/Applications/Firefox.app/Contents/MacOS/firefox-bin", "firefox_profile": "UEsDBBQAAAAIAPK6PUlBOpIx6gMAAKMOAAAHAAAAdXNlci5qc51XwW7jNhC99ysWOXWBmkg23Ut7SrMpUGCxKdYI9khQ1MhiTJFccmjFf98hZSF2LFFOb5LMIWfevPc4jgE8dx6aX69qgcKDsx6V2TBntZJ7lj6uY9WpEJQ1/+aPd1KCQ6ivfvvQCB3g45+/xKNtbMc68cJl620HPEivHHIfDUfVAcXcXp8G9FDVXu3oHYyoNHAjkF457MBgmD4ErdVbhcwA9tZvO2HEBjyrVUg7UAz6+CYkgIxe4Z71whu+U9BTmbxTL1Cz0NqeWyNh+rRnsRNDHcw6JBxCjvjH3NOjnTkPXhBMyIujIxiBDeXNwHaaHlUOPuXXg9hOB1Te9vTGHp6+3rFbJl6bcp6LcO6iJEZYETR0gH7PPDyDnNt2TCGA8LI9nFDONogG8nPiWCc0VbuQ06HFrEV0iVgraY2hnBKyKwd+RUuJPBR8c12CVIPYJUTzV1hq+akYWhAa2+GdpfOUBNYoH/B7NNMbvLJahBBJCNEQgIGg5KSlmBMuIEqnY3TMEa1p4TsKu4AslrLyqp6m7bgSRRXy/o/m0cFMka8EyPYQ0BKyHnK9DcmfSy9COx17rg9jUTX7p5CxKUlEBnfgTDmtZEWk8tr2rI6dO+JZUa6yBbm9t50jH6qUTicatWlR7xdQODStJd87NO5KVDbiH5UWZns1HaWpdE/2WFbB6KrLdvo2C7IQLZMTR6/LGdWwSwYQGOVjvRy8rQhawVPLUNmm0crMtK9UARN1rZL2xUIxJ7bhWhXa/Sr97EiOKw1mg4mXnz5/nrX6UuGOyO0wJJXwztZCL3Rv3k203WzSxwPcD6VtJk20ePCLU6RKoTULakP3KhlEIIH+jMovHtIChWUtfIFGRI1/Db+86/4qmdL5bfPOy2noQl7/ac4BeqOtqNk4ISTb/9GCWSeOUYLzajvMEtyS+/E65mrSVmXUiNVblkOSofiBpjPJGeiJP4nh/5s941102WjRKA30REbllURuvSLq8WHSK5flQdQJTsA8Dfydrr47ykcuDz+VtnKrVcDLrvmhUauDQayIvBhnhsACLtGlVhXFdJTiqMGS4o9GKBHRziBNIrOG0Oqgq8Cv8+tM9oWBb2k4OScbUWm46M7ZdlRnSvzLQOu1pLgwMTSdkpMtXhpF3S9OWaSzoWOcPIo/B1JNGmPVgNp5F179rG8VGUGiVdnOjuawPCEfzWESPE4fMzEE3Wsb5u6rEwhC+reEnPIsWN8F/7WK5B3lQayktmpNKFd7Xg8+Xb6qRxN4q/7budFONyG6QVUDGWYGGfpUP5ofmYbh5popAto+ff962RhEduu02EP9cHO9/kaTYObM77T4P1BLAQIUAxQAAAAIAPK6PUlBOpIx6gMAAKMOAAAHAAAAAAAAAAAAAACkgQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAA8EAAAAAA==", "args": [], "marionette": false}}
DEBUG 2016-09-29 23:23:39,126 remote_connection 85800 140735118328576 Finished Request
DEBUG 2016-09-29 23:23:39,127 remote_connection 85800 140735118328576 POST http://127.0.0.1:60960/hub/session/f8517508-33ac-314b-8671-6428b0545704/url {"url": "http://weixin.sogou.com/", "sessionId": "f8517508-33ac-314b-8671-6428b0545704"}
ERROR 2016-09-29 23:23:40,084 downloaders 85800 140735118328576 ''
Traceback (most recent call last):
  File "/Users/onestar/wechat_spider/wechat-spider/wechat/downloaders.py", line 101, in download_wechat
    self.visit_wechat_index(wechatid)
  File "/Users/onestar/wechat_spider/wechat-spider/wechat/downloaders.py", line 163, in visit_wechat_index
    browser.get("http://weixin.sogou.com/")
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
DEBUG 2016-09-29 23:23:40,092 remote_connection 85800 140735118328576 DELETE http://127.0.0.1:60960/hub/session/f8517508-33ac-314b-8671-6428b0545704/cookie {"sessionId": "f8517508-33ac-314b-8671-6428b0545704"}
ERROR 2016-09-29 23:23:40,093 downloaders 85800 140735118328576 [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/onestar/wechat_spider/wechat-spider/wechat/downloaders.py", line 49, in __exit__
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 655, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 432, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 61] Connection refused
```
os ： mac osx

看不太懂 debug 信息啊

**Comment by yijingping** [comment]
mac osx下，确保版本是 firefox 36.0，使用最新的版本会报错

**Comment by onestarshang** [comment]
好的~感谢~！我试试！ @yijingping

**Comment by onestarshang** [comment]
可以用了~！！！炸裂~！👏
