### ISSUE TITLE
downloader异常

### ISSUE THREAD

**Issue by wittyprince** [bowenpay/wechat-spider#74]
ERROR 2018-04-06 19:45:13,705 downloaders 42787 139981865047872 Message: Unable to locate element: {"method":"xpath","selector":"//div[@class='txt-box']/p[@class='info']/label"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/driver-component.js:10723)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/driver-component.js:10732)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/command-processor.js:12614)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/command-processor.js:12619)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/command-processor.js:12561)
Traceback (most recent call last):
  File "/home/wangchen/wechat-spider/wechat/downloaders.py", line 102, in download_wechat
    if self.visit_wechat_topic_list(wechatid):
  File "/home/wangchen/wechat-spider/wechat/downloaders.py", line 188, in visit_wechat_topic_list
    element_wechat = browser.find_element_by_xpath("//div[@class='txt-box']/p[@class='info']/label")
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 258, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: Unable to locate element: {"method":"xpath","selector":"//div[@class='txt-box']/p[@class='info']/label"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/driver-component.js:10723)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/driver-component.js:10732)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/command-processor.js:12614)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/command-processor.js:12619)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpbmGJMJ/extensions/fxdriver@googlecode.com/components/command-processor.js:12561)

**Comment by yijingping** [comment]
看着应该是搜狗微信的页面又改版了。 累觉不爱，不打算维护了
wittyprince <notifications@github.com>于2018年4月8日 周日上午10:05写道：
