### ISSUE TITLE
downloader报错

### ISSUE THREAD

**Issue by hziling** [bowenpay/wechat-spider#9]
EBUG 2016-09-30 01:30:19,049 __init__ 16368 139946394367808 version=0.2.2
DEBUG 2016-09-30 01:30:19,050 __init__ 16368 139946394367808 version=0.1.5
DEBUG 2016-09-30 01:32:27,583 downloader 16368 139946394367808 {u'kind': 3, u'word': u'\u6c7d\u8f66'}
DEBUG 2016-09-30 01:32:27,648 __init__ 16368 139946394367808 param: "['Xvfb', '-help']" 
DEBUG 2016-09-30 01:32:27,648 __init__ 16368 139946394367808 command: ['Xvfb', '-help']
DEBUG 2016-09-30 01:32:27,648 __init__ 16368 139946394367808 joined command: Xvfb -help
DEBUG 2016-09-30 01:32:27,652 __init__ 16368 139946394367808 process was started (pid=16511)
DEBUG 2016-09-30 01:32:27,658 __init__ 16368 139946394367808 process has ended
DEBUG 2016-09-30 01:32:27,658 __init__ 16368 139946394367808 return code=0
DEBUG 2016-09-30 01:32:27,658 __init__ 16368 139946394367808 stdout=
DEBUG 2016-09-30 01:32:27,658 __init__ 16368 139946394367808 stderr=use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
-br                    create root window with black background
+bs                    enable any backing store support
-bs                    disable any backing store support
-c                     turns off key-click
c #                    key-click volume (0-100)
-cc int                default color visual class
-nocursor              disable the cursor
-core                  generate core dump on fatal error
-displayfd fd          file descriptor to write display number to when ready to connect
-dpi int               screen resolution in dots per inch
-dpms                  disables VESA DPMS monitor control
-deferglyphs [none|all|16] defer loading of [no|all|16-bit] glyphs
-f #                   bell base (0-100)
-fc string             cursor font
-fn string             default font name
-fp string             default font path
-help                  prints message with these options
+iglx                  Allow creating indirect GLX contexts
-iglx                  Prohibit creating indirect GLX contexts (default)
-I                     ignore all remaining arguments
-ld int                limit data space to N Kb
-lf int                limit number of open files to N
-ls int                limit stack space to N Kb
-nolock                disable the locking mechanism
-nolisten string       don't listen on protocol
-listen string         listen on protocol
-noreset               don't reset after last client exists
-background [none]     create root window with no background
-reset                 reset after last client exists
-p #                   screen-saver pattern duration (minutes)
-pn                    accept failure to listen on all ports
-nopn                  reject failure to listen on all ports
-r                     turns off auto-repeat
r                      turns on auto-repeat 
-render [default|mono|gray|color] set render color alloc policy
-retro                 start with classic stipple and cursor
-s #                   screen-saver timeout (minutes)
...skipping...
[+-]accessx [ timeout [ timeout_mask [ feedback [ options_mask] ] ] ]
                       enable/disable accessx key sequences
-ardelay               set XKB autorepeat delay
-arinterval            set XKB autorepeat interval
-screen scrn WxHxD     set screen's width, height, depth
-pixdepths list-of-int support given pixmap depths
+/-render                  turn on/off RENDER extension support(default on)
-linebias n            adjust thin line pixelization
-blackpixel n          pixel value for black
-whitepixel n          pixel value for white
-fbdir directory       put framebuffers in mmap'ed files in directory
-shmem                 put framebuffers in shared memory
DEBUG 2016-09-30 01:48:26,340 __init__ 16368 139946394367808 param: "['Xvfb', '-br', '-screen', '0', '1024x768x24', ':1039']" 
DEBUG 2016-09-30 01:48:26,340 __init__ 16368 139946394367808 command: ['Xvfb', '-br', '-screen', '0', '1024x768x24', ':1039']
DEBUG 2016-09-30 01:48:26,341 __init__ 16368 139946394367808 joined command: Xvfb -br -screen 0 1024x768x24 :1039
DEBUG 2016-09-30 01:48:26,341 __init__ 16368 139946394367808 param: "['Xvfb', '-br', '-screen', '0', '1024x768x24', ':1024']" 
DEBUG 2016-09-30 01:48:26,341 __init__ 16368 139946394367808 command: ['Xvfb', '-br', '-screen', '0', '1024x768x24', ':1024']
DEBUG 2016-09-30 01:48:26,341 __init__ 16368 139946394367808 joined command: Xvfb -br -screen 0 1024x768x24 :1024
DEBUG 2016-09-30 01:48:26,345 __init__ 16368 139946394367808 process was started (pid=19254)
DEBUG 2016-09-30 01:48:26,345 abstractdisplay 16368 139946394367808 DISPLAY=:1024
a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_jpg/8jicXEqfbKCUAjCpxfs4b5hhias7tnxiboQLktLJw4IWo2v4GmqO5dGrFvAcPpc3hHBaibDp1xyDEBqibSqkjB62mCA/0?wx_fmt=jpeg', 'http://img01.sogoucdn.com/net/a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_png/RiaJj5csONAHqPfr3HAk8Y8DooYYbUjBrpwx6bdgAtOI22DriaRLGicM8B9GicSMo39d25dsCZHmnoUqGLpKWrja0w/0?wx_fmt=png', 'http://img01.sogoucdn.com/net/a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_jpg/b2YlTLuGbKAvMUwYLakJaFCh537IS3Wia9qSia3OsRVb7uqNpF4WXzMmpGpzb3uRUxhVPLBhyMKSYyv4xShlHjmQ/0?wx_fmt=jpeg', 'http://img01.sogoucdn.com/net/a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_jpg/VabuFTIoksIgyojNsMA02n5u2j41Jq7qC763z79KQzalWNgzFwV8s8MsPdS0pAPiaf1QuJ6gXVeFECxy7kIhSqg/0?wx_fmt=jpeg', 'http://img01.sogoucdn.com/net/a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_jpg/sQCrvCH4KbFlREVmyNumxuYiaqSXOsc4yqCuBNTPn0ibQl1dwOCpuuTWAlibOGocYyeQTSF3Bs5QZ3vJgLTVOp9pw/0?wx_fmt=jpeg', 'http://img01.sogoucdn.com/net/a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_png/1vNs1G9cnWZpTJc2Jnp0bibo0zicjHWquSibCDgvOalANmuOYiaPE97aZa1Nnd7CyWv5ibB9kQuIS4lRpegLr0N2tgQ/0?wx_fmt=png', 'http://img01.sogoucdn.com/net/a/04/link?appid=100520031&url=http://mmbiz.qpic.cn/mmbiz_jpg/WSj0n9GPvlPo7bvqfzV1cTVoxfrPJUAwSVvre7hlOhia7VhCNcxgFB3jE8fjiaOiaRKggjdDBTAI6xicf0k9PPLv0w/0?wx_fmt=jpeg'] [u'\u60ac\u6302\u7cfb\u7edf\u60ac\u6302\u7684\u4f5c\u7528', u'\u8f66\u4e3b\u5982\u9047\u5230', u'\u4f3d\u5f6c\u5bfc\u8bed       \u7206\u80ce\u662f\u6307\u8f6e\u80ce\u5728\u6781\u77ed\u7684\u65f6\u95f4(\u4e00\u822c\u5c11\u4e8e0.1\u79d2)\u56e0\u7834\u88c2\u7a81\u7136\u5931\u53bb\u7a7a\u6c14\u800c\u762a\u6389.\u7206\u80ce\u662f', u'\u201c', u'\u8f6c\u8f7d\u81ea', u'1886\u5e741\u670829\u65e5,\u5fb7\u56fd\u4eba\u5361\u5c14\u2022\u672c\u8328\u4e3a\u5176\u57281885\u5e74\u7814\u5236\u6210\u529f\u7684\u4e09\u8f6e', u'\u968f\u7740\u56fd\u5e86\u9ec4\u91d1\u5468\u4e0d\u65ad\u4e34\u8fd1,\u5f88\u591a\u8ba1\u5212\u5229\u7528\u957f\u5047\u81ea\u9a7e\u6e38\u7684\u6d88\u8d39\u8005\u6700\u8fd1\u90fd\u5728\u96c6\u4e2d\u91c7\u8d2d', '', u'\u968f\u7740\u73b0\u4ee3', u'\u751a\u81f3\u662f\u6709\u4e9b\u8f66\u4e3b\u4e70\u4e86\u8f66\u4e4b\u540e\u5c31\u628a\u8f66\u6446\u5bb6\u95e8\u53e3\u4e0d\u52a8\u4e86,\u5916\u51fa\u4f9d\u65e7\u6324\u516c\u4ea4\u3001\u5730\u94c1,\u7f8e\u5176\u540d\u66f0\u201c\u73af\u4fdd\u51fa\u884c\u201d,\u800c\u5b9e\u9645\u4e0a\u5374\u662f\u56e0\u6b64\u6cb9\u8017\u592a\u9ad8\u3001\u6cb9\u4ef7\u592a\u8d35,\u90a3\u53eb\u4e00\u4e2a\u60b2\u50ac\u554a~\u8981\u8bf4\u5173\u4e4e\u517b...']
未被限制,可以下载
Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

Traceback (most recent call last):
  File "bin/downloader.py", line 96, in <module>
    downloader.run()
  File "bin/downloader.py", line 77, in run
    with SeleniumDownloaderBackend(proxy=proxy) as browser:
  File "/home/zzg/wechat-spider/wechat/downloaders.py", line 42, in __enter__
    self.browser = self.get_browser(self.proxy)
  File "/home/zzg/wechat-spider/wechat/downloaders.py", line 90, in get_browser
    browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 78, in __init__
    self.binary, timeout)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by yijingping** [comment]
你安装firefox了吗？ 是哪个版本？

**Comment by otamanager** [comment]
`selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
`
解决方法：Selenium下的是3.0，firefox是49.0，所以必须下载geckodriver,下载地址：https://github.com/mozilla/geckodriver/releases
下载完成后，解压并放到/usr/bin即可
